name: pub_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pub_semver: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^0.13.3
  pedantic: ^1.11.0
  test: ^1.16.8
